### ISSUE TITLE
Deploying 6-distributed-tensorflow

### ISSUE THREAD

**Issue by gary918** [wbuchwalter/tensorflow-k8s-azure#40]
Hi, all,

After deploying 6-distributed-tensorflow by using 'kubectl create -f', I can only find the tf-job for module6-ex1, but there's no job & pod. 

Does anyone know what the problem is?

Thanks.

**Comment by StefanoFioravanzo** [comment]
In order to debug the issue try to run `kubectl describe tfjob <name-of-tfjob>`

If you followed the tutorial as-is, you may probably need to refer to [this] (https://github.com/kubeflow/tf-operator/issues/351) issue. You need to add a Template to the PS replica in the yml file, just like for the master and workers.

**Comment by wbuchwalter** [comment]
Hi,
Since i wrote this content, kubeflow had numerous API changes.
It's in my plan to rework this in the coming days.

**Comment by gary918** [comment]
@StefanoFioravanzo  Thanks for your reply. Here is the debug info I got after adding the PS replica template. Would you please help check if there's anything wrong?
`gary@ubuntu1:~/tensorflow-k8s-azure/6-distributed-tensorflow/solution-src$ kubectl describe tfjob module6-ex1
Name:         module6-ex1
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  kubeflow.org/v1alpha1
Kind:         TFJob
Metadata:
  Cluster Name:                   
  Creation Timestamp:             2018-03-07T15:54:07Z
  Deletion Grace Period Seconds:  <nil>
  Deletion Timestamp:             <nil>
  Initializers:                   <nil>
  Resource Version:               143170
  Self Link:                      /apis/kubeflow.org/v1alpha1/namespaces/default/tfjobs/module6-ex1
  UID:                            c5066c7e-221f-11e8-937a-0a58ac1f0988
Spec:
  Replica Specs:
    Replicas:  1
    Template:
      Spec:
        Containers:
          Image:              wbuchwalter/tf-mnist:distributed
          Image Pull Policy:  Always
          Name:               tensorflow
          Volume Mounts:
            Mount Path:  /tmp/tensorflow
            Name:        azurefile
            Sub Path:    module6-ex1
        Restart Policy:  OnFailure
        Volumes:
          Azure File:
            Read Only:    false
            Secret Name:  azure-secret
            Share Name:   tensorflow
          Name:           azurefile
    Tf Replica Type:      MASTER
    Replicas:             2
    Template:
      Spec:
        Containers:
          Image:              wbuchwalter/tf-mnist:distributed
          Image Pull Policy:  Always
          Name:               tensorflow
        Restart Policy:       OnFailure
    Tf Replica Type:          WORKER
    Replicas:                 1
    Template:
      Spec:
        Containers:
          Image:              wbuchwalter/tf-mnist:distributed
          Image Pull Policy:  Always
          Name:               tensorflow
        Restart Policy:       OnFailure
    Tf Replica Type:          PS
  Tensorboard:
    Log Dir:       /tmp/tensorflow/logs
    Service Type:  LoadBalancer
    Volume Mounts:
      Mount Path:  /tmp/tensorflow
      Name:        azurefile
      Sub Path:    module6-ex1
    Volumes:
      Azure File:
        Secret Name:  azure-secret
        Share Name:   tensorflow
      Name:           azurefile
Events:               <none>
`

**Comment by wbuchwalter** [comment]
@gary918 this looks good to me.
If you cannot see the pods, do `kubectl get pods -a` because they might already be completed.

**Comment by gary918** [comment]
@wbuchwalter  It works. Thanks!

I also got the following log with errors from the master pod.  Do you have any clues about the root cause?

2018-03-07 17:04:41.729803: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
E0307 17:04:41.730227393       1 ev_epoll1_linux.c:1051]     grpc epoll fd: 3
2018-03-07 17:04:41.736488: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job master -> {0 -> localhost:2222}
2018-03-07 17:04:41.736544: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job ps -> {0 -> mnist-ps-u1j4-0:2222}
2018-03-07 17:04:41.736582: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job worker -> {0 -> mnist-worker-u1j4-0:2222, 1 -> mnist-worker-u1j4-1:2222}
2018-03-07 17:04:41.737266: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:324] Started server with target: grpc://localhost:2222
2018-03-07 17:04:42.931807: I tensorflow/core/distributed_runtime/master_session.cc:1004] Start master session 5c62456edd5070be with config: 
Extracting /tmp/tensorflow/input_data/train-images-idx3-ubyte.gz
Extracting /tmp/tensorflow/input_data/train-labels-idx1-ubyte.gz
Extracting /tmp/tensorflow/input_data/t10k-images-idx3-ubyte.gz
Extracting /tmp/tensorflow/input_data/t10k-labels-idx1-ubyte.gz
Traceback (most recent call last):
  File "/app/main.py", line 251, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/app/main.py", line 224, in main
    train()
  File "/app/main.py", line 193, in train
    with sv.prepare_or_wait_for_session(server.target) as sess:  
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 708, in prepare_or_wait_for_session
    init_feed_dict=self._init_feed_dict, init_fn=self._init_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 273, in prepare_session
    config=config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 205, in _restore_checkpoint
    saver.restore(sess, ckpt.model_checkpoint_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1666, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /tmp/tensorflow/logs/model.ckpt-0: Not found: /tmp/tensorflow/logs; No such file or directory
	 [[Node: save/RestoreV2_14 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:ps/replica:0/task:0/device:CPU:0"](_recv_save/Const_0_S1, save/RestoreV2_14/tensor_names, save/RestoreV2_14/shape_and_slices)]]

Caused by op u'save/RestoreV2_14', defined at:
  File "/app/main.py", line 251, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/app/main.py", line 224, in main
    train()
  File "/app/main.py", line 191, in train
    logdir=FLAGS.logdir)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 300, in __init__
    self._init_saver(saver=saver)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 448, in _init_saver
    saver = saver_mod.Saver()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 751, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 427, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 267, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 1021, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on /tmp/tensorflow/logs/model.ckpt-0: Not found: /tmp/tensorflow/logs; No such file or directory
	 [[Node: save/RestoreV2_14 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:ps/replica:0/task:0/device:CPU:0"](_recv_save/Const_0_S1, save/RestoreV2_14/tensor_names, save/RestoreV2_14/shape_and_slices)]]
