### ISSUE TITLE
module6-ex1: wrong volume path setting ? 

### ISSUE THREAD

**Issue by gary918** [wbuchwalter/tensorflow-k8s-azure#41]
Hi, all,
I got the following error when I log the master pod of module6-ex1. Does it mean that I have set the wrong volume path? Thanks in advance!

gary@ubuntu1:~/tensorflow-k8s-azure/6-distributed-tensorflow/solution-src$ kubectl logs module6-ex1-master-ucsz-0-j2gtd
2018-03-08 06:40:43.944326: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
E0308 06:40:43.944684225       1 ev_epoll1_linux.c:1051]     grpc epoll fd: 3
2018-03-08 06:40:43.950551: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job master -> {0 -> localhost:2222}
2018-03-08 06:40:43.950603: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job ps -> {0 -> module6-ex1-ps-ucsz-0:2222}
2018-03-08 06:40:43.950628: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job worker -> {0 -> module6-ex1-worker-ucsz-0:2222, 1 -> module6-ex1-worker-ucsz-1:2222}
2018-03-08 06:40:43.950915: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:324] Started server with target: grpc://localhost:2222
2018-03-08 06:40:45.948658: I tensorflow/core/distributed_runtime/master_session.cc:1004] Start master session 370b786090d8459b with config: 
Extracting /tmp/tensorflow/input_data/train-images-idx3-ubyte.gz
Extracting /tmp/tensorflow/input_data/train-labels-idx1-ubyte.gz
Extracting /tmp/tensorflow/input_data/t10k-images-idx3-ubyte.gz
Extracting /tmp/tensorflow/input_data/t10k-labels-idx1-ubyte.gz
Traceback (most recent call last):
  File "/app/main.py", line 251, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/app/main.py", line 224, in main
    train()
  File "/app/main.py", line 193, in train
    with sv.prepare_or_wait_for_session(server.target) as sess:  
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 708, in prepare_or_wait_for_session
    init_feed_dict=self._init_feed_dict, init_fn=self._init_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 273, in prepare_session
    config=config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 205, in _restore_checkpoint
    saver.restore(sess, ckpt.model_checkpoint_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1666, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /tmp/tensorflow/logs/model.ckpt-0: Not found: /tmp/tensorflow/logs; No such file or directory
	 [[Node: save/RestoreV2_14 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:ps/replica:0/task:0/device:CPU:0"](_recv_save/Const_0_S1, save/RestoreV2_14/tensor_names, save/RestoreV2_14/shape_and_slices)]]

Caused by op u'save/RestoreV2_14', defined at:
  File "/app/main.py", line 251, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/app/main.py", line 224, in main
    train()
  File "/app/main.py", line 191, in train
    logdir=FLAGS.logdir)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 300, in __init__
    self._init_saver(saver=saver)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 448, in _init_saver
    saver = saver_mod.Saver()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 751, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 427, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 267, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 1021, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on /tmp/tensorflow/logs/model.ckpt-0: Not found: /tmp/tensorflow/logs; No such file or directory
	 [[Node: save/RestoreV2_14 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:ps/replica:0/task:0/device:CPU:0"](_recv_save/Const_0_S1, save/RestoreV2_14/tensor_names, save/RestoreV2_14/shape_and_slices)]]

**Comment by gary918** [comment]
Got it. In order to match the directories: /tmp/tensorflow/input_data, /tmp/tensorflow/logs, the 'subPath' items should be removed in the yaml file.
